name: Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  create_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hello-world:latest

  push-image:

    runs-on: ubuntu-latest

    steps:
      - name: Build and Push to DockerHub
        uses: MaximilianoBz/dockerhub-buildpush@v1.1
        with:
          registry_url: docker.io
          
          repository_name: fkron95/fk-demo
        
          user_name: ${{ secrets.DOCKERHUB_USERNAME }}

          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
          image_version: latest
      
          docker_file: .
              
