name: Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  create-and-push-image:

    runs-on: ubuntu-latest

    steps:
      - name: Build and Push to DockerHub
        uses: MaximilianoBz/dockerhub-buildpush@v1.1
        with:
          registry_url: docker.io
          
          repository_name: fkron95/fk-demo
        
          user_name: ${{ secrets.DOCKERHUB_USERNAME }}

          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
          image_version: latest
      
          docker_file: Dockerfile
              
