# This is a basic workflow to help you get started with Actions

name: env_test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains job called "env_variables"
  env_variables:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Environment variables
    env:
      GREET: "Hello"
      QUESTION: "How are you"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Greeting
        run: |
          echo "$GREET my friend"
          
      - name: Question for the person
        run: |
          echo "$QUESTION today?"
